### ISSUE TITLE
PointOfSale violates software licenses of its components

### ISSUE THREAD

**Issue by ghost** [tualo/PointOfSale#1]
@thomashoffmann1979, to be absolutely honest I am a little bit disappointed you do not respect [software licenses of free software](https://github.com/petrkutalek/png2pos/blob/master/LICENSE) you have used as components in your solution.
### (c) 2012 - 2015 Petr Kutalek: png2pos

> Licensed under the MIT License: Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software")… , to deal in the Software without restriction… subject to the following conditions:
> **The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software**…
### (c) 2005 - 2014 Lode Vandevenne: LodePNG

> Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
> …If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required… **This notice may not be removed or altered from any source distribution.**

I hope this is just a misunderstanding and you are going to fix this copyright infringement as soon as possible. Thanks a lot.

**Comment by thomashoffmann1979** [comment]
Oh, you are right. Of course we respect your copyright. This program is still under development and not published to customers. An i missed to add the license, while experimenting with submodule or including the source directly. Now i have added that license in the source code of escimage.cpp and at the users frontend side on About.qml. We don't use lodePNG, so we didn't at that license. Instead we use QImage to open image files.

I am sorry.

**Comment by ghost** [comment]
Thank you. I appreciate that.
